<a href="https://colab.research.google.com/github/idrissdeme/Projetos-Python-IRD/blob/main/Projeto_Samuel_IRD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Projeto: Indices de SRS
### Samuel Façanha

In [ ]:
import pandas as pd

In [ ]:
pd.options.display.float_format = '{:20,.2f}'.format

Para saber mais sobre essa mudança de formato, [consulte a documentação](https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html).

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Exibindo a tabela completa**

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/Trabalho Python/modelo indices SRS.xlsx')
#display(df)
df

,Índices de qualidade para SRS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Paciente: Dayane,NaN,NaN,NaN,NaN,NaN,NaN
1,Protuário: 586172,NaN,NaN,NaN,NaN,NaN,NaN
2,Medico(a): Sarah,NaN,NaN,NaN,NaN,NaN,NaN
3,Fisico: Samuel,NaN,NaN,NaN,NaN,NaN,NaN
4,Alvo,PTV,Tolerancia,NaN,Precrição,NaN,NaN
5,Vrx (vol da dose de presc) =,11.51,NaN,NaN,PTV,5 x 6Gy,NaN
6,Vptv (vol do PTV) =,10.55,NaN,NaN,NaN,NaN,NaN
7,RTOG CI =,1.09,"(1 - 2; ~1,4 mult alvos)",NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,SRS,NaN,NaN
9,V50%rx (vol da isod de 50%) =,39.38,NaN,NaN,Critério,2% / 2mm - 95%,NaN
10,V100%rx (vol da isod de 100%)=,11.51,NaN,NaN,Arco,% de aprovação,NaN
11,Paddick GI =,3.42,(3 - 5),NaN,1,96.80,ok
12,NaN,NaN,NaN,NaN,2,95,ok
13,Dmax (dose máxima) =,3290,NaN,NaN,3,98,ok
14,Drx (dose de prescrição) =,3000,NaN,NaN,NaN,NaN,NaN
15,RTOG HI =,1.10,"1 - 2 ; 1,44",NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Vol isod de 50%,39.38,NaN,NaN,NaN,NaN,NaN
18,Vol PTV,10.55,NaN,NaN,NaN,NaN,NaN
19,C50 (cobert da dose interm) =,3.73,"(3 - 7,5)",NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Dose max,3290,NaN,NaN,NaN,NaN,NaN
22,Dose mín,"2,846.50",NaN,NaN,NaN,NaN,NaN
23,HI' =,1.16,"(<=2; 1,30 - 1,10)",NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,OAR`s,Valor atual,Limite,NaN,NaN,NaN,NaN
26,Cerebro,19cc,V24 < 20cc,NaN,NaN,NaN,NaN

**Exibindo apenas a identificação do paciente, físico e médico**

In [ ]:
df.rename(columns={'Índices de qualidade para SRS':'Dados demográficos'}, inplace = True)

In [ ]:
df['Dados demográficos'][0:4]

0     Paciente: Dayane
1    Protuário: 586172
2     Medico(a): Sarah
3       Fisico: Samuel
Name: Dados demográficos, dtype: object

**Exibindo a prescrição**

In [ ]:
df.iloc[[4,5],[4,5]]

  Unnamed: 4 Unnamed: 5
4  Precrição        NaN
5        PTV    5 x 6Gy

**Exibindo apenas as variáveis obitidas do planejamento**

In [ ]:
df.rename(columns={'Dados demográficos':'Dados do planejamento'}, inplace = True)

In [ ]:
df.iloc[[5,6,9,10,13,14,17,18,21,22],[0,1]]

             Dados do planejamento           Unnamed: 1
5     Vrx (vol da dose de presc) =                11.51
6              Vptv (vol do PTV) =                10.55
9    V50%rx (vol da isod de 50%) =                39.38
10  V100%rx (vol da isod de 100%)=                11.51
13            Dmax (dose máxima) =                 3290
14      Drx (dose de prescrição) =                 3000
17                 Vol isod de 50%                39.38
18                         Vol PTV                10.55
21                        Dose max                 3290
22                        Dose mín             2,846.50

**Exibindo os índices e o intervalo de tolerancia para cada um deles**

In [ ]:
df.rename(columns={'Dados do planejamento':'Índices'}, inplace = True)

In [ ]:
df.iloc[[4,7,11,15,19,23],[0,2]]

                          Índices                 Unnamed: 2
4                            Alvo                 Tolerancia
7                       RTOG CI =   (1 - 2; ~1,4 mult alvos)
11                   Paddick GI =                    (3 - 5)
15                      RTOG HI =               1 - 2 ; 1,44
19  C50 (cobert da dose interm) =                  (3 - 7,5)
23                          HI' =         (<=2; 1,30 - 1,10)

**Cálculo dos índices e avaliação**

In [ ]:
df1 =df

In [ ]:
df1['Unnamed: 1'][7]=df['Unnamed: 1'][5]/df['Unnamed: 1'][6]
if 1<=df['Unnamed: 1'][7]<=2:
  df1['Unnamed: 3'][7] = "Aprovado"


else:
  df1['Unnamed: 3'][7] = "Reprovado"

df1.iloc[[7],[0,1,3]]

     Índices           Unnamed: 1 Unnamed: 3
7  RTOG CI =                 1.09   Aprovado

In [ ]:
df1['Unnamed: 1'][11]=df['Unnamed: 1'][9]/df['Unnamed: 1'][10]
if 3<=df['Unnamed: 1'][11]<=5:
  df1['Unnamed: 3'][11] = "Aprovado"


else:
  df1['Unnamed: 3'][11] = "Reprovado"

df1.iloc[[11],[0,1,3]]

         Índices           Unnamed: 1 Unnamed: 3
11  Paddick GI =                 3.42   Aprovado

In [ ]:
df1['Unnamed: 1'][15]=df['Unnamed: 1'][13]/df['Unnamed: 1'][14]
if 1<=df['Unnamed: 1'][15]<=2:
  df1['Unnamed: 3'][15] = "Aprovado"


else:
  df1['Unnamed: 3'][15] = "Reprovado"

df1.iloc[[15],[0,1,3]]

      Índices           Unnamed: 1 Unnamed: 3
15  RTOG HI =                 1.10   Aprovado

In [ ]:
df1['Unnamed: 1'][19]=df['Unnamed: 1'][17]/df['Unnamed: 1'][18]
if 3<=df['Unnamed: 1'][19]<=7.5:
  df1['Unnamed: 3'][19] = "Aprovado"


else:
  df1['Unnamed: 3'][19] = "Reprovado"

df1.iloc[[19],[0,1,3]]

                          Índices           Unnamed: 1 Unnamed: 3
19  C50 (cobert da dose interm) =                 3.73   Aprovado

In [ ]:
df1['Unnamed: 1'][23]=df['Unnamed: 1'][21]/df['Unnamed: 1'][22]
if df['Unnamed: 1'][23]<=2:
  df1['Unnamed: 3'][23] = "Aprovado"


else:
  df1['Unnamed: 3'][23] = "Reprovado"

df1.iloc[[23],[0,1,3]]

   Índices           Unnamed: 1 Unnamed: 3
23   HI' =                 1.16   Aprovado

**Dose nos OAR's**

In [ ]:
df.rename(columns={'Índices':'Constraints para OAR'}, inplace = True)

In [ ]:
df.iloc[[25,26],[0,1,2]]

   Constraints para OAR   Unnamed: 1   Unnamed: 2
25                OAR`s  Valor atual       Limite
26              Cerebro         19cc   V24 < 20cc

In [ ]:
if df['Unnamed: 1'][26]<='20cc':
  df1['Unnamed: 3'][26] = "Aprovado"


else:
  df1['Unnamed: 3'][26] = "Reprovado"

df1.iloc[[26],[0,1,3]]

   Constraints para OAR Unnamed: 1 Unnamed: 3
26              Cerebro       19cc   Aprovado

**Controle da Qualidade**

In [ ]:
if df1['Unnamed: 5'][11]>=95:
  df1['Unnamed: 6'][11] = "Aprovado"

else:
  df1['Unnamed: 6'][11] = "Reprovado"


if df1['Unnamed: 5'][12]>=95:
  df1['Unnamed: 6'][12]= "Aprovado"

else:
  df1['Unnamed: 6'][12]= "Reprovado"


if df1['Unnamed: 5'][13]>=95:
  df1['Unnamed: 6'][13]= "Aprovado"

else:
  df1['Unnamed: 6'][13]= "Reprovado"

df.iloc[[9,10,11,12,13],[4,5,6]]

   Unnamed: 4           Unnamed: 5 Unnamed: 6
9    Critério       2% / 2mm - 95%        NaN
10       Arco       % de aprovação        NaN
11          1                96.80   Aprovado
12          2                   95   Aprovado
13          3                   98   Aprovado

# Exportar como CSV ou excel

Para exportar o DataFrame como um arquivo CSV, use o método `to_csv`, indicando o caminho onde deseja que seu arquivo seja salvo. Se você não quiser incluir o índice do DataFrame, especifique usando `index=False`.

In [ ]:
df1.to_excel('meu_arquivo.xlsx', index=True)